import React, { useState } from 'react';

export default function Home() {
  const [currentTab, setCurrentTab] = useState(0);

  const showTab = (n) => {
    const x = document.getElementsByClassName("tab");
    // x[n].style.display = "block";
    if (n === 0) {
      document.getElementById("prevBtn").style.display = "none";
    } else {
      document.getElementById("prevBtn").style.display = "inline";
    }
    if (n === (x.length - 1)) {
      document.getElementById("nextBtn").innerHTML = "Submit";
    } else {
      document.getElementById("nextBtn").innerHTML = "Next";
    }
    fixStepIndicator(n);
  };

  const nextPrev = (n) => {
    const x = document.getElementsByClassName("tab");
    if (n === 1 && !validateForm()) return false;
    x[currentTab].style.display = "none";
    setCurrentTab(currentTab + n);
    if (currentTab >= x.length) {
      document.getElementById("regForm").submit();
      return false;
    }
    showTab(currentTab);
  };

  const validateForm = () => {
    let x, y, i, valid = true;
    x = document.getElementsByClassName("tab");
    y = x[currentTab].getElementsByTagName("input");
    for (i = 0; i < y.length; i++) {
      if (y[i].value === "") {
        y[i].className += " invalid";
        valid = false;
      }
    }
    if (valid) {
      document.getElementsByClassName("step")[currentTab].className += " finish";
    }
    return valid;
  };

  const fixStepIndicator = (n) => {
    let i, x = document.getElementsByClassName("step");
    for (i = 0; i < x.length; i++) {
      x[i].className = x[i].className.replace(" active", "");
    }
    x[n].className += " active";
  };

  return (
    <div >
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <form id="regForm" action="/action_page.php">
        <h1>Register:</h1>
        {/* <!-- One "tab" for each step in the form: --> */}
        <div className="tab">Name:
          <p>
            <input placeholder="First name..." oninput="this.className = ''" name="fname" />
            </p>
          <p>
            <input placeholder="Last name..." oninput="this.className = ''" name="lname" />
            </p>
        </div>
        <div className="tab">Contact Info:
          <p>
            <input placeholder="E-mail..." oninput="this.className = ''" name="email" /></p>
          <p>
            <input placeholder="Phone..." oninput="this.className = ''" name="phone" /></p>
        </div>
        <div className="tab">Birthday:
          <p>
            <input placeholder="dd" oninput="this.className = ''" name="dd" />
            </p>
          <p>
            <input placeholder="mm" oninput="this.className = ''" name="nn" />
            </p>
          <p>
            <input placeholder="yyyy" oninput="this.className = ''" name="yyyy" />
            </p>
        </div>
        <div className="tab">Login Info:
          <p>
            <input placeholder="Username..." oninput="this.className = ''" name="uname" />
            </p>
          <p>
            <input placeholder="Password..." oninput="this.className = ''" name="pword" type="password" />
          </p>
        </div>
        <div >  {/*style="overflow:auto;" */}
          <div >  {/*style="float:right;" */}
            <button type="button" id="prevBtn" onClick="nextPrev(-1)">Previous</button>
            <button type="button" id="nextBtn" onClick="nextPrev(1)">Next</button>
          </div>
        </div>
        {/* <!-- Circles which indicates the steps of the form: --> */}
         <div style={{textAlign: 'center', marginTop: '40px', }}> {/*  */}
          <span className="step"></span>
          <span className="step"></span>
          <span className="step"></span>
          <span className="step"></span>
        </div>
      </form>


    </div>
  )
}
